refactor of security auth client and add spring security filter
AtlasOfLivingAustralia/ala-security-project pull request #10
Opened 2022-09-08 02:30 UTC by brucehyslop

The added implementation of pac4j auth client (`AlaAuthClient`) to chain through a list of implementations of `AlaDirectClient` (`AlaOidcClient`, `AlaApiKeyClient`, `AlaIpWhitelistClient`).
Switched interceptor to use `AlaAuthClient`
Created implementation of spring security filter `AlaWebServiceAuthFilter`
upgrade to grade 7.2

2022-09-16 01:37 UTC, sbearcsiro requested changes
Hey Bruce, this is all great, just needs some clean up IMHO to de-springify and remove component scan and make the http calls mockable.

2022-09-16 01:37 UTC, sbearcsiro commented on build.gradle
> +    api 'org.springframework.security:spring-security-web:5.7.3'
This dependency seems out of place in this plugin?

2022-09-16 01:37 UTC, sbearcsiro commented on src/main/groovy/au/ala/org/ws/security/AlaWsSecurityGrailsPluginConfiguration.groovy
> +@ComponentScan('au.org.ala.ws.security')
I don't particularly like this, component scan is slow when your contains a lot of JARS, I'd rather keep all the Spring stuff in this `@Configuration` class, remove Spring annotations from the actual classes and then use `spring.factories` pointing at this class.  This way you don't have to inject Properties classes, etc, the classes themselves remain properly testable without spring, etc, etc.

2022-09-16 01:37 UTC, sbearcsiro commented on src/main/groovy/au/org/ala/ws/security/authenticator/AlaApiKeyAuthenticator.groovy
> +        HTTPRequest apiKeyRequest = new HTTPRequest(HTTPRequest.Method.GET, URI.create("${apiKeyUri}/${apiKey}"))
IMHO These HTTP calls should be extracted to eg a retrofit interface dependency so that they can be unit tested without spinning up an HTTP server.

2022-09-16 01:37 UTC, sbearcsiro commented on src/main/groovy/au/org/ala/ws/security/authenticator/AlaApiKeyAuthenticator.groovy
> +        HTTPRequest userDetailsRequest = new HTTPRequest(HTTPRequest.Method.POST, URI.create(userDetailsUri))
You could use the existing userdetails service client for this request

2022-09-16 01:37 UTC, sbearcsiro commented on src/main/groovy/au/org/ala/ws/security/authenticator/AlaOidcAuthenticator.groovy
> +        this.keySource = new RemoteJWKSet(configuration.findProviderMetadata().JWKSetURI.toURL(), configuration.findResourceRetriever())
This should probably be injected instead of newed here for easier testing.

2022-09-16 01:37 UTC, sbearcsiro commented on src/test/groovy/au/org/ala/ws/security/authenticator/AlaApiKeyAuthenticatorSpec.groovy
> +        WireMockServer wm = new WireMockServer(wireMockConfig().dynamicPort())
I'm not a fan of using an http server in our unit tests tbh

2022-10-05 00:12 UTC, brucehyslop commented
> Hey Bruce, this is all great, just needs some clean up IMHO to de-springify and remove component scan and make the http calls mockable.

Refactored the configuration to remove component scan annotation and declare beans in configuration class (see: [6a0200e](https://github.com/AtlasOfLivingAustralia/ala-ws-security-plugin/pull/10/commits/6a0200ecb71412308310ef8f5e667b82ebe3d8a0))

2022-12-02 03:35 UTC, sbearcsiro approved these changes

2022-12-02 03:35 UTC, merged